import bpy,json,os,pathlib
from mathutils import Vector
out=pathlib.Path(os.environ['CIVIC_MODEL_ROOT'])/'CalibrationRound3';working=bpy.data.scenes['CIVIC_BLOCKS_FACADES_WORKING'];r=json.load(open(out/'gongzhong_offset_comparison.json'));candidate=r['first_mall_clear_candidate'];assert candidate;offset=Vector(candidate['translation']);name='CAL3_GONGZHONG_CORE_COMPARISON';assert not bpy.data.collections.get(name);col=bpy.data.collections.new(name);working.collection.children.link(col);scene=bpy.data.scenes.new('GONGZHONG_CORE_OFFSET_COMPARISON');scene.collection.children.link(col);scene.world=working.world
objects=[o for o in working.objects if o.type=='MESH' and (o.name.startswith('COMP_\u516c\u4e2d_CORE0_L') or o.name.startswith('RAIL_CORE_\u516c\u4e2d_0_'))];counts={}
for label,delta,color in [('ORIGINAL',Vector(),(.85,.34,.1,1)),('OFFSET_5M',offset,(.12,.65,.42,1))]:
 for source in objects:
  o=source.copy();o.name='GZ_'+label+'_'+source.name;col.objects.link(o);o.location+=delta;o.color=color;o['comparison_status']='Unadopted estimate; only selected underground-mall clearance sampled';o['source_object']=source.name
 counts[label]=len(objects)
center=Vector((871,785,-3.6))+offset*.5;cd=bpy.data.cameras.new('GZ_CORE_DETAIL_REVIEW');cam=bpy.data.objects.new('GZ_CORE_DETAIL_REVIEW',cd);col.objects.link(cam);cam.location=center+Vector((-8,-15,10));cam.rotation_euler=(center-cam.location).to_track_quat('-Z','Y').to_euler();cd.type='ORTHO';cd.ortho_scale=18;scene.camera=cam;scene.render.engine='BLENDER_WORKBENCH';scene.render.resolution_x=1280;scene.render.resolution_y=900;scene.render.resolution_percentage=100;scene.display.shading.color_type='OBJECT';scene.display.shading.show_shadows=False;scene.display.shading.show_cavity=True;scene.render.image_settings.file_format='PNG';scene.render.filepath=str(out/'GONGZHONG_CORE_5M_COMPARISON.png');working.view_layers[0].layer_collection.children[col.name].exclude=True;bpy.ops.render.render(write_still=True,scene=scene.name)
report={'scene':scene.name,'counts':counts,'original_color':'orange','alternative_color':'green','offset_m':candidate['along_offset_m'],'translation':candidate['translation'],'adopted':False,'limits':r['scope'],'handrail_detail':'Both copies use new estimated handrails seated on existing modeled treads. No stair openings relocated in working assembly.'};(out/'gongzhong_comparison_model.json').write_text(json.dumps(report,indent=2));bpy.context.window.scene=working;working.frame_set(1);bpy.ops.wm.save_as_mainfile(filepath=bpy.data.filepath);result=report
