import bpy,bmesh,json,pathlib,datetime
from mathutils import Vector
root=pathlib.Path('/Users/ktlu/Desktop/Civic_Rebuild_20260909_201934');out=root/'Y26Orientation';rows=json.load(open(out/'connection_payload.json'));stamp=datetime.datetime.now().strftime('%Y%m%d_%H%M%S');bpy.ops.wm.save_as_mainfile(filepath=str(out/('before_connections_'+stamp+'.blend')),copy=True);mat=bpy.data.materials.new('Y26_CONNECTION_EST');mat.diffuse_color=(.15,.55,.55,1);qa=[]
cam=bpy.data.objects['Y26_PHOTO_REVIEW'];prior=cam.matrix_world.copy();scale=cam.data.ortho_scale
for r in rows:
 col=bpy.data.collections['Y26_PHOTO_CONFIGURATION_ESTIMATED' if r['variant']=='A' else 'Y26_BUILDING_AXIS_ALTERNATIVE'];sc=bpy.data.scenes['Y26_PHOTO_COMPARISON' if r['variant']=='A' else 'Y26_ORIENTATION_COMPARISON']
 for p in r['parts']:
  name='Y26_'+p['name'];assert not bpy.data.objects.get(name);me=bpy.data.meshes.new(name);me.from_pydata(p['mesh']['vertices'],[],p['mesh']['faces']);me.update();bm=bmesh.new();bm.from_mesh(me);bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces));bad=sum(not e.is_manifold for e in bm.edges);assert bad==0;bm.to_mesh(me);bm.free();o=bpy.data.objects.new(name,me);col.objects.link(o);me.materials.append(mat);o['status']=r['status'];qa.append({'object':name,'nonmanifold_edges':bad})
 floor=bpy.data.objects['Y26_'+r['variant']+'_LOWER_LANDING_CONNECTION'];center=sum((v.co for v in floor.data.vertices),Vector())/len(floor.data.vertices);cam.location=center+Vector((13,-17,10));cam.rotation_euler=(center-cam.location).to_track_quat('-Z','Y').to_euler();cam.data.ortho_scale=25;sc.render.filepath=str(out/('Y26_'+r['variant']+'_connection.png'));bpy.ops.render.render(write_still=True,scene=sc.name)
cam.matrix_world=prior;cam.data.ortho_scale=scale;file=out/('CIVIC_Y26_CONNECTIONS_'+stamp+'.blend');bpy.ops.wm.save_as_mainfile(filepath=str(file));report={'file':str(file),'parts':qa,'variants':[{k:v for k,v in r.items() if k!='parts'} for r in rows],'limits':'New geometry is in separate comparison collections. B requires approx5.1m approach to legacy shell plus overlap. Existing mall wall has not been opened; neither proposal is verified as-built or end-to-end traversable.'};(out/'connection_check.json').write_text(json.dumps(report,ensure_ascii=False,indent=2));result=report
