import bpy,json,pathlib,os
from mathutils import Vector
out=pathlib.Path(os.environ['CIVIC_MODEL_ROOT'])/'CalibrationRound3';sc=bpy.data.scenes['CIVIC_BLOCKS_FACADES_WORKING'];assert not bpy.data.collections.get('CAL3_MACHINE_ROOM_DOORS');col=bpy.data.collections.new('CAL3_MACHINE_ROOM_DOORS');sc.collection.children.link(col);mat=bpy.data.materials.get('CAL3_MACHINE_DOOR_STEEL') or bpy.data.materials.new('CAL3_MACHINE_DOOR_STEEL');mat.diffuse_color=(.22,.28,.3,1);bright=bpy.data.materials.new('CAL3_MACHINE_HANDLE');bright.diffuse_color=(.65,.68,.7,1);faces=[(0,3,2,1),(4,5,6,7),(0,1,5,4),(1,2,6,5),(2,3,7,6),(3,0,4,7)];rows=[];payload=json.load(open(out/'machine_room_door_payload.json'))
for r in payload:
 old=bpy.data.objects[r['source']];org=Vector(r['origin']);u=Vector((*r['u'],0));f=Vector((*r['f'],0));left,right=r['door_left'],r['door_right'];y=r['front_y'];height=r['door_height_assumed_m'];zmax=r['top_z']-r['floor_z'];created=[]
 def boxes(suffix,parts,material):
  vs=[];fs=[]
  for x0,x1,y0,y1,z0,z1 in parts:
   off=len(vs)
   for x,yy,z in [(x0,y0,z0),(x1,y0,z0),(x1,y1,z0),(x0,y1,z0),(x0,y0,z1),(x1,y0,z1),(x1,y1,z1),(x0,y1,z1)]:vs.append(tuple(u*x+f*yy+Vector((0,0,z))))
   fs.extend([tuple(off+i for i in p) for p in faces])
  m=bpy.data.meshes.new(old.name+'_'+suffix);m.from_pydata(vs,[],fs);m.materials.append(material);m.update();o=bpy.data.objects.new(old.name+'_'+suffix,m);o.location=org;col.objects.link(o);o['source_object']=old.name;o['status']=r['status'];created.append(o.name);return o
 boxes('DOOR_LINTEL',[(left,right,y-.15,y,height,zmax)],old.data.materials[0]);boxes('DOOR_FRAME',[(left,left+.06,y-.16,y+.02,0,height),(right-.06,right,y-.16,y+.02,0,height),(left+.06,right-.06,y-.16,y+.02,height-.06,height)],mat);boxes('DOOR_LEAF',[(left+.067,right-.067,y-.075,y-.025,.02,height-.067)],mat);boxes('DOOR_HANDLE',[(right-.23,right-.2,y-.025,y+.07,.92,1.08)],bright);boxes('DOOR_HINGES',[(left+.045,left+.085,y-.03,y+.005,z,z+.1) for z in [.25,1.,1.75]],bright);rows.append({'source':old.name,'objects':created,'door_width_m':right-left,'door_height_assumed_m':height})
# Isolated close-up scene without route-camera timeline bindings.
review=bpy.data.scenes.new('MACHINE_ROOM_DOOR_DETAIL_REVIEW');review.world=sc.world;rc=bpy.data.collections.new('CAL3_MACHINE_ROOM_REVIEW_ONLY');review.collection.children.link(rc);r=next(p for p in payload if '\u516c\u4e2d' in p['source']);source=r['source'];targets=[bpy.data.objects[source]]+[o for o in col.objects if o.get('source_object')==source];equipment=source.replace('MACHINE_ROOM','MACHINE_BLOCK')
if equipment in bpy.data.objects:targets.append(bpy.data.objects[equipment])
for o in targets:rc.objects.link(o)
org=Vector(r['origin']);u=Vector((*r['u'],0));f=Vector((*r['f'],0));cd=bpy.data.cameras.new('MACHINE_DOOR_REVIEW_CAMERA');cam=bpy.data.objects.new('MACHINE_DOOR_REVIEW_CAMERA',cd);rc.objects.link(cam);cam.location=org+f*10+u*6+Vector((0,0,6));aim=org+Vector((0,0,1.2));cam.rotation_euler=(aim-cam.location).to_track_quat('-Z','Y').to_euler();cd.type='ORTHO';cd.ortho_scale=10;review.camera=cam;review.render.engine='BLENDER_WORKBENCH';review.render.resolution_x=1200;review.render.resolution_y=850;review.render.resolution_percentage=100;review.display.shading.color_type='MATERIAL';review.display.shading.show_shadows=False;review.display.shading.show_cavity=True;review.render.image_settings.file_format='PNG';review.render.filepath=str(out/'MACHINE_ROOM_DOOR_DETAIL.png');bpy.ops.render.render(write_still=True,scene=review.name);bpy.context.window.scene=sc;sc.frame_set(1);bpy.ops.wm.save_as_mainfile(filepath=bpy.data.filepath);report={'rooms_detailed':len(rows),'new_objects':len(col.objects),'existing_shells_preserved':True,'vent_openings_changed':False,'door_state':'closed','rooms':rows,'limits':'Door heights and hardware estimated; actual door locations only follow the prior estimated model, not surveyed entrances. Internal machinery remains generic blocks.'};(out/'machine_room_door_report.json').write_text(json.dumps(report,indent=2));result={k:v for k,v in report.items() if k!='rooms'}
