import bpy,json
from pathlib import Path
root=Path(bpy.data.filepath).parent/'PierPositions_20260924'
scene=bpy.data.scenes['CIVIC_PIER_XY_REVIEW_20260923']
jobs=[('p234_missing_north_review.json', 'apply_missing_support_observations.py'), ('p233_position_review.json', 'apply_observation_set_xy.py'), ('west233_position_review.json', 'apply_observation_set_xy.py'), ('west233_missing_south_review.json', 'apply_missing_support_observations.py'), ('antong_west_position_review.json', 'apply_observation_set_xy.py'), ('huaisheng_position_review.json', 'apply_observation_set_xy.py'), ('huaisheng_west_position_review.json', 'apply_observation_set_xy.py'), ('huaisheng_footbridge_position_review.json', 'apply_observation_set_xy.py'), ('west_footbridge_position_review.json', 'apply_observation_set_xy.py'), ('west_portal_position_review.json', 'apply_observation_set_xy.py'), ('ramp_merge_position_review.json', 'apply_observation_set_xy.py'), ('blue_portal_position_review.json', 'apply_observation_set_xy.py'), ('west_blue_portal_position_review.json', 'apply_observation_set_xy.py'), ('west_blue_portal_south_position_review.json', 'apply_observation_set_xy.py'), ('painted_church_position_review.json', 'apply_observation_set_xy.py'), ('painted_temple_position_review.json', 'apply_observation_set_xy.py'), ('ramp_screen_end_position_review.json', 'apply_observation_set_xy.py'), ('west_screen_white_missing_review.json', 'apply_missing_support_observations.py'), ('west_white_next_position_review.json', 'apply_observation_set_xy.py'), ('jianguo_east_intermediate_missing_review.json', 'apply_missing_support_observations.py'), ('jianguo_east_edge_position_review.json', 'apply_observation_set_xy.py'), ('jianguo_west_edge_position_review.json', 'apply_observation_set_xy.py'), ('p214_position_review.json', 'apply_observation_set_xy.py'), ('west_p214_position_review.json', 'apply_observation_set_xy.py'), ('west_p214_next_position_review.json', 'apply_observation_set_xy.py'), ('local_junction_east_position_review.json', 'apply_observation_set_xy.py'), ('local_junction_west_position_review.json', 'apply_observation_set_xy.py'), ('p209_position_review.json', 'apply_observation_set_xy.py'), ('west_p209_position_review.json', 'apply_observation_set_xy.py'), ('west_p209_next_position_review.json', 'apply_observation_set_xy.py'), ('songjiang_east_position_review.json', 'apply_observation_set_xy.py'), ('east_visible_p147_position_review.json', 'apply_observation_set_xy.py'), ('ramp_east_portal_position_review.json', 'apply_observation_set_xy.py'), ('west_visible_p147_position_review.json', 'apply_observation_set_xy.py'), ('zhonglin_access_west_position_review.json', 'apply_observation_set_xy.py')]
checks=[]
for filename,script in jobs:
 records=json.loads((root/filename).read_text())['targets']
 if all(bool(r.get('comparison_object')) and r['comparison_object'] in scene.objects for r in records):
  checks.append({'file':filename,'already_present':True});continue
 assert not any(bool(r.get('comparison_object')) and r['comparison_object'] in scene.objects for r in records),'Partial application needs review'
 code=(root/script).read_text().replace('scene=bpy.context.scene',"scene=bpy.data.scenes['CIVIC_PIER_XY_REVIEW_20260923']")
 ns={'INPUT_FILE':filename};exec(compile(code,script,'exec'),ns)
 checks.append(ns['result'])
result={'checks':checks,'scope':'XY only; original scene retained. No automatic road widening, height or cap edits.'}
