import bpy,json,os
from mathutils import Vector
root=os.path.join(os.path.dirname(bpy.data.filepath),'Underbridge_20260922')
data=json.loads("{\"batch_name\":\"UB_GUANGFU_SERVICE_HOUSE_EST\",\"observations\":[{\"pano\":\"GZMhNyE7IicA0gM0V4WQJg\",\"lat\":25.0450688,\"lon\":121.5569551,\"date\":\"2025-01\",\"heading\":90,\"observed\":[\"tall louvred service enclosure\",\"arched door hood\",\"picket fence\"],\"dimensions_verified\":false,\"status\":\"partial_ground_view\"}],\"masses\":[{\"id\":\"HOUSE\",\"center\":[4713,410,2.18],\"size\":[30,6,4],\"material\":\"stone\",\"kind\":\"box\",\"angle\":12,\"pano\":\"GZMhNyE7IicA0gM0V4WQJg\",\"segment\":\"UB_X+047\",\"placement_note\":\"Photo-visible service enclosure near Guangfu. Dimensions/XY estimated; hood is a simplified mass rather than measured curved profile.\"},{\"id\":\"GRILLE\",\"center\":[4712.36690890146,412.97845944423443,2.2],\"size\":[22,0.08,2.9],\"material\":\"louvre\",\"kind\":\"box\",\"angle\":12,\"pano\":\"GZMhNyE7IicA0gM0V4WQJg\",\"segment\":\"UB_X+047\",\"placement_note\":\"Photo-visible service enclosure near Guangfu. Dimensions/XY estimated; hood is a simplified mass rather than measured curved profile.\"},{\"id\":\"DOOR\",\"center\":[4698.28376934696,406.8719686116468,1.44],\"size\":[0.08,1.6,2.5],\"material\":\"louvre\",\"kind\":\"box\",\"angle\":12,\"pano\":\"GZMhNyE7IicA0gM0V4WQJg\",\"segment\":\"UB_X+047\",\"placement_note\":\"Photo-visible service enclosure near Guangfu. Dimensions/XY estimated; hood is a simplified mass rather than measured curved profile.\"},{\"id\":\"HOOD\",\"center\":[4697.691990048516,406.74618203870205,2.8],\"size\":[1.5,2,0.4],\"material\":\"roof\",\"kind\":\"hip\",\"angle\":12,\"pano\":\"GZMhNyE7IicA0gM0V4WQJg\",\"segment\":\"UB_X+047\",\"placement_note\":\"Photo-visible service enclosure near Guangfu. Dimensions/XY estimated; hood is a simplified mass rather than measured curved profile.\"},{\"id\":\"FENCE\",\"center\":[4712.043606222238,414.4994789633755,1.08],\"size\":[30,0.12,1.8],\"material\":\"louvre\",\"kind\":\"box\",\"angle\":12,\"pano\":\"GZMhNyE7IicA0gM0V4WQJg\",\"segment\":\"UB_X+047\",\"placement_note\":\"Photo-visible service enclosure near Guangfu. Dimensions/XY estimated; hood is a simplified mass rather than measured curved profile.\"}],\"full_corridor_complete\":false}")
for item in data['masses']:
 o=bpy.data.objects[data['batch_name']+'_'+item['id']+'_EST'];vs=[o.matrix_world@v.co for v in o.data.vertices]
 z=min(v.z for v in vs) if item['kind']=='hip' else (min(v.z for v in vs)+max(v.z for v in vs))/2
 center=Vector(((min(v.x for v in vs)+max(v.x for v in vs))/2,(min(v.y for v in vs)+max(v.y for v in vs))/2,z));target=Vector(item['center']);delta=o.matrix_world.inverted().to_3x3()@(target-center)
 for v in o.data.vertices:v.co+=delta
 o.data.update()
json.dump(data,open(os.path.join(root,'guangfu_service_manifest.json'),'w'),ensure_ascii=False,indent=2)
bpy.ops.wm.save_as_mainfile(filepath=bpy.data.filepath)
result={'aligned_facade_parts':True,'dimensions_verified':False}